# Generated by Django 2.2.5 on 2021-10-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='')),
                ('caption', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
                ('thumnail_img', models.ImageField(upload_to='')),
                ('tag', models.CharField(max_length=40)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('category', models.CharField(choices=[('교과대학', '교과대학'), ('인문대학', '인문대학'), ('경영대학', '경영대학'), ('경영대학', '경영대학'), ('농식품융합대학', '농식품융합대학'), ('약학대학', '약학대학'), ('사범대학', '사범대학'), ('자연과학대학', '자연과학대학'), ('한의과대학', '한의과대학'), ('조형예술디자인대학', '조형예술디자인대학'), ('창의공과대학', '창의공과대학'), ('치과대학', '치과대학'), ('의과대학', '의과대학')], default='일반', max_length=20)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
